server:
    port: 9041
    session:
      timeout: 1800

spring:
    profiles:
        active: dev-tb
    thymeleaf:
      cache: false

mybatis-plus:
    global-config:
        db-column-underline: true
        field-strategy: 1
        id-type: 2
        refresh-mapper: true
    mapper-locations: classpath:/mapper/*Dao.xml
    type-aliases-package: com.ks.sharding.pojo
    configuration:
        jdbc-type-for-null: 'null'


login:
    excludePathPatterns: /test/*